site_name: Figma
site_url: https://www.figma.com/

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  static_templates:
    - 404.html

  palette:
    # Dark Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: "#18A0FB"
      accent: "#FF7262"

    # Light Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: "#18A0FB"
      accent: "#FF7262"

nav:
  - Home: index.md
  - Creating a Figma Design: create-file.md
  - Good Design Practices: good-design-practices.md
  - What is a prototype?: what-is-prototype.md
  - Presenting and Sharing Prototypes: presenting-prototypes.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Shabnam-Beiraghian
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/robyn-downie-480b0920b/
copyright: Copyright &copy; 2025 BuiltByRobyn & Shabnam-Beiraghian
